### ISSUE TITLE
Icons don't update status

### ISSUE THREAD

**Issue by zmoazeni** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#25]
Hi there,

I'm using Cinnamon (3.6.7) on Arch and have noticed that icons don't update their status.

I'm basing this off of both the Package Manager (turns red when updates are available) and Slack (electron, but displays a blue circle with activity, and a red circle when a direct message comes through).

I've tried both having it in the active area and hidden area.

**Comment by Feuerfuchs** [comment]
That's strange. I use Arch and Cinnamon 3.6.7 as well and the few icons I have (pamac, bluetooth, redshift) update just fine. Do you have the same problem with Cinnamon's built-in system tray? Does restarting Cinnamon (Alt+F2, type r, enter) help?

**Comment by zmoazeni** [comment]
I don't have that problem with the built-in system tray.

I did also try restarting and even toggling an app between hidden/shown states in the collapsible tray and neither seemed to do the trick.

Messing with it again this morning, I realize it's only a problem with inactive applications. Active applications do update appropriately.

To give you an idea of my use case. I'm not a fan of Slack's blue dot (some activity in a room, but not a direct message to you) or even sometimes the Arch Update turning red. They're both neat visual notifications, but if I'm focusing on things, I would rather just hide it (or periodically check it). So I mark both of them as inactive. That way on hover, I'll see if anything new has happened. I use the Win 10 system bar similarly too.

**Comment by Feuerfuchs** [comment]
Unfortunately, the way system tray icons work in Cinnamon doesn't leave much room to fix such kind of issues. The whole hiding process is a horrible hack.

But there is one thing we can try: There was a similar issue with Pidgin and to have it not freeze, it gets some special treatment in the hiding process. Maybe that works for Slack and the other icons as well.

Can you please list all icons that are affected by this bug? I need the exact names as shown in the context menu since these are used to identify each icon.

**Comment by zmoazeni** [comment]
Ah right on. Thanks for taking a stab at this. I'm currently hiding:

* `pamac-tray` The Antergos Package Manager updater
* `slack` Slack installed from slack-desktop in AUR
* `unknown` Dropbox :( the `dropboxc` package in the antergos repository.

**Comment by Feuerfuchs** [comment]
Oh, Dropbox still works for you? The version I use (`dropbox` package) stopped working altogether a long time ago. It neither gives an id ("unknown" was the string in older versions, now it's just an empty string), nor does the icon actually show up. It's just a blank spot.

Anyway, I pushed a new branch which contains the (hopefully working) fix for these icons: https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/tree/issue-25
You can just grab the file `collapsible-systray@feuerfuchs.eu/applet.js` and put it into `~/.local/share/cinnamon/applets/collapsible-systray@feuerfuchs.eu`, then restart Cinnamon.

**Comment by zmoazeni** [comment]
@Feuerfuchs Just tested it. Unfortunately no go (at least with slack). Not sure on the package manager, that might be fixed.

Dropbox does work for me. At least in terms of being able to right click the icon and open preferences or whatever.

**Comment by Feuerfuchs** [comment]
Turns out it's just the AppIndicator support that's broken in newer Dropbox versions. :) Apart from that, I played around to see if I could actually replicate this issue, but to no avail.

I pushed one more commit, and I hope that one fixes your problem. Installation works the same way as before.
If this fix doesn't work, then I'm afraid I'm already out of options.

**edit:** Oh no, that one makes icons not hide correctly anymore. They turn invisible, but remain clickable. I think that was the reason why my currently solution turned out to be such a hack...

You see, tray icons in Cinnamon each sit in their own GtkWindow, just without borders etc. But you can do usual window operations on them such as hiding them. That's what I use in my applet to circumvent the above problem.

**Comment by zmoazeni** [comment]
@Feuerfuchs That does work. I think there's a bit of a flicker as the hover expands (not sure if that was there before or not), but the icons are updated. Thanks!

**Comment by zmoazeni** [comment]
> Oh no, that one makes icons not hide correctly anymore. They turn invisible, but remain clickable. I think that was the reason why my currently solution turned out to be such a hack...

Hrm, I'm not seeing that on my side.

**Comment by Feuerfuchs** [comment]
> Hrm, I'm not seeing that on my side.

It's quite tricky to notice. When the system tray is collapsed, clicking anywhere in the area to the right of the expand/collapse button can result in opening a tray icon's context menu.

**Comment by zmoazeni** [comment]
My tray expands to the left, but I've been trying that (clicking to the left of the expand button after it collapses) and I'm not seeing that here. That's weird.

**Comment by zmoazeni** [comment]
Ahh I think I see it now (or a result of it). I hovered over an icon to the right of the the collapsible menu and yeah, I click and it's going to a hidden icon instead of what I'm visually seeing.

Damn.

**Comment by Feuerfuchs** [comment]
Alright, so this issue boils down to the fact that I use this fancy sliding animations for showing and hiding icons. If it weren't for those, I could actually use a way less error-prone method to hide icons, but it is incompatible with any kind of animation.

So my plan is now as follows: I will add a setting to enable a "compatibility mode". This one will use the more stable but also ugly-looking method.

> Ahh I think I see it now (or a result of it). I hovered over an icon to the right of the the collapsible menu and yeah, I click and it's going to a hidden icon instead of what I'm visually seeing.

Damn, I was already writing an explanation why that will happen to you, too, sooner or later. Oh well, can't let that go to waste so here you are. :P

My tray opens to the left as well. The reason why the icons end up to the right of the applet is because the when the parent container reaches a width of 0, the virtual horizontal scrolling I use to keep the icons' position static during the animation process can't compute their position anymore, and so they default to left alignment. Since the parent container is 0 pixels wide, its left edge is now exactly where it's right edge is — right of the collapse/expand button. So now that all icons are left-aligned in that container, they overflow to the right side.  
If tray icons worked like any other UI object, they would be invisible and unclickable if they overflow their parent container. But tray icons are actually GtkWindows and these don't care about overflows. They just keep track of where the icon is positioned in the tray and that's how they end up to the right of the applet.

This behavior was horrible to debug when I started working on the applet. :/
