### ISSUE TITLE
Broken on Cinnamon 3.8.0

### ISSUE THREAD

**Issue by telmotrooper** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#26]
I know you just got around to fixing the shaking on collapsing/expanding the tray (thank you for that, by the way) but it seems the new Cinnamon 3.8.0 broke the applet. :(

**Comment by Feuerfuchs** [comment]
In what way is it broken? And do you use the latest version? [jaszhix updated the code](https://github.com/linuxmint/cinnamon-spices-applets/pull/1683) to make it compatible with Cinnamon 3.8 so it should work. But that being said, I can't confirm it does because the latest version in the Manjaro repositories is still 3.6.2...

**Comment by telmotrooper** [comment]
I just installed the applet from the git repository instead of from the Applets dialog to guarantee I have the latest version, but the problem remains. When attempting to load the applet it says that it is not compatible with the latest version of Cinnamon and if I just load it anyway, it doesn't show in my panel.

Here are the pictures to make it clearer: https://imgur.com/a/bxpCvYj

By the way, Cinnamon 3.8.0 is available in the community repository in Arch.

**Comment by Feuerfuchs** [comment]
Cinnamon 3.8 is finally available in the Manjaro repos. By the way, Manjaro is always updated with a slight delay, so what's available in Arch isn't necessarily available in Manjaro yet. ;)

Anyway, I can finally reproduce your issue and find a way to fix it!
