### ISSUE TITLE
Click area just in the icon

### ISSUE THREAD

**Issue by DanielRios549** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#27]
I have used this applet for a while, and a bug that is bothering me is that, I have do click exactly on the icon to active it or active the tray menu, if I click outside the icon, it brings me the applet menu, this is nothing productive. In the images, I clicked both with right button.
![screenshot from 2018-06-03 13-30-29](https://user-images.githubusercontent.com/11152535/40888815-4cad291c-6733-11e8-8dda-2924551eec6b.png)
![screenshot from 2018-06-03 13-30-44](https://user-images.githubusercontent.com/11152535/40888816-4ccf038e-6733-11e8-8008-afc4724ac43a.png)

**Comment by Feuerfuchs** [comment]
That's unfortunately a problem I can't fix as tray icons aren't handled in the same way as other UI elements. Here's what happens if I make the icon's UI actor fill the available height:

![bildschirmfoto vom 2018-06-03 19-10-51](https://user-images.githubusercontent.com/14197353/40889142-db5a6e12-6761-11e8-8592-d52f864efda8.png)

It depends on every single tray icon how it adapts to its UI actor being resized. As you can see, the standard behavior is that the icon scales with the click area while retaining its aspect ratio, thus getting clipped. Only Dropbox works fine, but then again, it refuses to adapt to my HiDPI display and is extremely small...

Anyway, there's nothing I can do.

**Comment by Feuerfuchs** [comment]
I checked Cinnamon's source code to see if there's really nothing that can be done and as it turns out, I was too hasty: There's a fake click event for all tray icons available which can be exploited to enlarge the click area.

**Comment by DanielRios549** [comment]
Perfect, I was writing something like that, if there is something to use the click outside the icon to call the icon click, either left or right. I don't have idea how to change this code, otherwise I would help you, but if you be succeed, it will be a nice enhancement for this applet

**Comment by Feuerfuchs** [comment]
I have no idea how I didn't notice how annoying it was having to click the icons precisely. It's so much better now. Thanks for this suggestion!

**Comment by DanielRios549** [comment]
Wow, you are fast man, thank you so much for attention
