### ISSUE TITLE
Cinnamon 4.2.0 support

### ISSUE THREAD

**Issue by telmotrooper** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#35]
With Cinnamon 4.2.0 released (at least on Arch), Collapsible Systray doesn't work anymore. 

Could you give this a look?

Thank you so much! 😀️

**Comment by Pandiora** [comment]
Just a quick fix that might work:
- create a folder named "4.2.0" and put in all files that are located in folder "4.0.0" too
- update the manifest.json to match the cinnamon version

**Comment by telmotrooper** [comment]
@Pandiora Just had the time to give that a try and it actually worked, so thanks! ☺️

Since the initial issue the Cinnamon package on Arch has been bumped to 4.2.2, so:

I went to the directory `~/.local/share/cinnamon/applets/collapsible-systray@feuerfuchs.eu`, copied the folder `4.0` and named the copy `4.2.2`. I then edited the `metadata.json` to to include `4.2.2` in the `cinnamon-version` array.

With that done the applet started working as usual.

**Comment by Pandiora** [comment]
I did that too recently but forgot to report back. :( There might be some way to tell cinnamon to use the extension no matter what, but I've no idea how. The applet-manager even tells you the extension is outdated and if you want to use it anyway and if you click "Ok" nothing happens. So this is kinda broken it seems. I hope they will add an refurbished version of this extension in the future like they did for IcingTaskManager - but for this to happen some more features need to be implemented and bugs resolved and performance improved.

**Comment by Odyseus** [comment]
Hello, everybody.

@telmotrooper and @Pandiora: You don't need to duplicate the **4.0** folder inside the applet folder; Cinnamon will use that folder when the applet is enabled in any version greater than or equal to **4.0.x** (at least in theory). You just need to add **4.2** to the **cinnamon-version** array in the **metadata.json** file. And don't use micro versions (e.g. **4.2.2**), otherwise you will have to edit the **metadata.json** file every single time Cinnamon is updated to a micro version.

@Pandiora: When the applet manager informs you that the applet isn't compatible and you decide to load it anyway, the applet is enabled and loaded, but not displayed in the panel. This part of Cinnamon's behaviour is a total and absolute nonsense so, the best thing to do when you see that message is to click **Cancel** and report to the author of the xlet that the xlet needs updating. Or simply edit the **cinnamon-version** array in the **metadata.json** file yourself (or completely delete the **cinnamon-version** key).

**Comment by Pandiora** [comment]
@Odyseus thx for the info, I wasn't aware the folder doesn't needs to be duplicated anymore and now it makes more sense to have this setting in the manifest. (or maybe I just did it wrong all the time - just copied what IcingTaskManager was doing and the docs back then were incomplete to say the least)

Depending the feature to use the extension anyway: I wonder if it is intentional the applet doesn't gets displayed if I tell so. Not everyone, like feuerfuchs here, has the time to maintain his applet and keep up with the updates of cinnamon, repectively Mint. Deleting the versions entirely could be a way to circumvent these reoccuring problems with applets, but I bet devs at Mint Project won't like it, nor accept it if an author submits such applets. I believe this should be fixed on Cinnamon/Mint side and not by applet authors. If so I might work again on my applet (monitoring graph of remote systems + cli remote control) and publish it to the cinnamon repo. This current state of cinnamon and the still bad performance and inconsistencies (which aren't caused by cinnamon) are making it difficult to publish something that lasts at least some years and I don't wanna maintain something simple every now and then. An applet or xlet like feuerfuchs' here should be the standard!

P.S.: I remember why IcingTaskManager were using different folders for different versions: I think it was when cinnamon got updated to version 3.x, the underlying API changed and this way rendered dozens of applets unusable. So it is still a good idea to use numbered folders for main-versions like 3.0,4.0,5.0.
